# ruff: noqa: RUF001 — Korean text for staff-facing shotlist
"""Korean text fields (P0 rows) for photo shotlist. Keys = suggested_filename."""

P0: dict[str, dict[str, str]] = {
    "src/img/photos/home/hero-clinic-exterior-golden-hour.webp": {
        "section": "메인 히어로(동영상·포스터 대체용, /hero-video.mp4)",
        "current_state": "동영상 + /main.jpeg 포스터",
        "photo_subject": "골든아워의 압구정 병원 외부 와이드. 골드 포인트 조명, 간판 식별 용이. 동영상 미로딩·억제 시 <video poster>로 사용.",
        "composition": "와이드",
        "orientation": "가로 16:9",
        "mood_lighting": "따뜻한 골든아워, 프리미엄 톤",
        "must_include": "튠의원(또는 클리닉) 식별 간판, 5층 전면, 깔끔한 상가 외관",
        "must_avoid": "행인 얼굴, 자동차 번호판, 동일 화면에 경쟁 클리닉 식별 간판",
        "consent_required": "없음",
        "count": "각도 3장 + 최종 1장",
        "notes": "OG용 1:1 정사각 크롭도. 수평선 3분할, 좌하단에 헤드라인·텍스트 오버레이 여백.",
    },
    "src/img/photos/home/hero-interior-signature.webp": {
        "section": "메인 히어로(실내 대체 포스터)",
        "current_state": "동영상 + /main.jpeg 포스터",
        "photo_subject": "상담실 또는 메인 복도 시그니처 실내. 골드 포인트·웜우드, 가장자리는 어둡게(화이트 타이틀 가독).",
        "composition": "와이드",
        "orientation": "가로 16:9",
        "mood_lighting": "은은한 뮤지엄톤, 따뜻한 텅스텐",
        "must_include": "실내 골드 테두리·우드·식물, 정돈된 면",
        "must_avoid": "얼굴(동의 없을 때), 환자 소지품, 유리 눈부심",
        "consent_required": "없음",
        "count": "각도 2장",
        "notes": "보조 포스터. 왼쪽 40% 네거티브 스페이스(헤드라인용).",
    },
    "src/img/photos/home/why-apgujeong-streetview.webp": {
        "section": "Why Apgujeong(신뢰 스트립, 124행 부근)",
        "current_state": "텍스트만",
        "photo_subject": "5층 창가에서의 압구정 로데 거리, 또는 보도에서 건물을 올려다보는 뷰(지구 맥락).",
        "composition": "와이드",
        "orientation": "가로 3:2",
        "mood_lighting": "밝은 주광, 살짝 낮은 채도(프리미엄 느낌)",
        "must_include": "압구정 거리(부티크·가로수) 식별 가능",
        "must_avoid": "얼굴 식별되는 행인, 허락 없는 명품 악센트 로고",
        "consent_required": "없음",
        "count": "2장",
        "notes": "외국인 환자 가이드·압구정 페이지에 재사용.",
    },
    "src/img/photos/home/inside-clinic-reception.webp": {
        "section": "Inside the Clinic(다크 CTA, 1256행)",
        "current_state": "텍스트만",
        "photo_subject": "리셉션 데스크, 컨시어지(뒷머리만 또는 합의된 인물), 램프, 골드 악센트.",
        "composition": "미디엄",
        "orientation": "가로 3:2",
        "mood_lighting": "따뜻한 텅스텐, 이브닝 느낌",
        "must_include": "카운터, 은은한 브랜드, 생화",
        "must_avoid": "환자 얼굴, 모니터 가격, 이름 적힌 서류",
        "consent_required": "필요(직원·초상)",
        "count": "각도 3장",
        "notes": "현재 100% 텍스트 — 이미지 투입 시 임팩트 큼.",
    },
    "src/img/photos/home/visit-us-5f-arrival.webp": {
        "section": "Visit Us(지도·주소 블록, 1335행)",
        "current_state": "텍스트만",
        "photo_subject": "5층 엘리베이터홀·클리닉 문 바로 앞 층수 안내(방문 동선).",
        "composition": "미디엄",
        "orientation": "가로 3:2",
        "mood_lighting": "밝은 클리니컬",
        "must_include": "층수 표기, 벽/문에 로고, 광택 바닥",
        "must_avoid": "다른 임대인 간판, 청소 카트",
        "consent_required": "없음",
        "count": "2장",
        "notes": "주소+지도 옆에 배치.",
    },
    "src/img/photos/booking/hero-consultation-desk-overhead.webp": {
        "section": "예약 Hero(4행)",
        "current_state": "텍스트·골드 밑줄만",
        "photo_subject": "탑뷰: 가죽 다이어리, 클리닉 명함, 만년필, 꽃 한 송이, (차/주 원장) 손이 플랜을 작성.",
        "composition": "탑뷰",
        "orientation": "가로 16:9",
        "mood_lighting": "좌측 데이라이트, 침·차분",
        "must_include": "흰 가운 소매, 브랜딩, 플랜 수첩",
        "must_avoid": "진짜 환자 이름, 개인이 보이는 화면",
        "consent_required": "필요(의사)",
        "count": "변형 3장",
        "notes": "의사와 함께하는 플랜’ 비주얼, 결정보호·디자인방식 재사용.",
    },
    "src/img/photos/booking/success-welcome-florals.webp": {
        "section": "예약 완료(성공) 화면(200행)",
        "current_state": "체크+텍스트",
        "photo_subject": "리셉션에 화이트·크림 꽃 + 환영 카드 클로즈(제출 직후 안심).",
        "composition": "클로즈업",
        "orientation": "정사각 1:1",
        "mood_lighting": "밝고 에어리",
        "must_include": "꽃, 브랜딩 카드/봉투",
        "must_avoid": "시기 티 나는 문구, 환자 이름",
        "consent_required": "없음",
        "count": "2장",
        "notes": "UX 고급화(선택).",
    },
    "src/img/photos/metacell/hero-prp-pbm-hands.webp": {
        "section": "메타셀 LP Hero(35행, 핵심 랜딩)",
        "current_state": "다크 그라데이션·텍스트",
        "photo_subject": "장갑 낀 손이 라벨된 PRP 원심분리 관을 들거나, PBM 헤드 전경. 시술실 보케.",
        "composition": "클로즈업",
        "orientation": "가로 16:9",
        "mood_lighting": "뮤지엄톤, 쿨·웜 스플릿",
        "must_include": "장갑, PRP 관·또는 PBM, 흰 가운 커프",
        "must_avoid": "‘줄기세포’ 등 오해 소지 문구(라벨), 환자 신체",
        "consent_required": "필요(의사)",
        "count": "변형 4장",
        "notes": "광고 런칭 핵심. 좌측 다크(화이트 헤드라인 가독).",
    },
    "src/img/photos/metacell/equipment-prp-centrifuge.webp": {
        "section": "자가 PRP·재생 설명(80행)",
        "current_state": "텍스트만",
        "photo_subject": "스텐 트레이 위 원심분리기·준비된 튜브(진행 중) 클리니컬 톤.",
        "composition": "미디엄",
        "orientation": "가로 3:2",
        "mood_lighting": "밝은 클리니컬",
        "must_include": "원심분리기, (튠 클리닉 라벨) 튜브, 장갑",
        "must_avoid": "지저분한 판, 유통기한 지난 라벨",
        "consent_required": "없음",
        "count": "각도 3장",
        "notes": "콜라겐·스킨부스터도 재사용.",
    },
    "src/img/photos/metacell/build-{ultherapy|thermage|pbm}-card.webp": {
        "section": "3가지 구성(109행, 카드 그리드)",
        "current_state": "텍스트만(3칸)",
        "photo_subject": "동일 조명: (a)울쎄라 핸드피스 (b)써마지 팁+기기 (c)PBM 헤드 — 정사각 셋이 정렬.",
        "composition": "클로즈업",
        "orientation": "정사각 1:1",
        "mood_lighting": "클리니컬+웜 림라이트",
        "must_include": "은은한 제품 밍, 먼지 없는 면",
        "must_avoid": "시리얼, 셋 간 조명 불일치",
        "consent_required": "없음",
        "count": "3장(구성당 1)",
        "notes": "연속 촬영으로 카드 격자 통일감.",
    },
    "src/img/photos/doctors/dr-cha-portrait-formal.webp": {
        "section": "차승연 원장 — 정식(반신) 초상(메디컬보드 893행 등)",
        "current_state": "이니셜/텍스트",
        "photo_subject": "대표·원장, 웜뉴트럴 벽, 자신감·차분, 시선은 카메라 살짝 옆.",
        "composition": "인물(세로)",
        "orientation": "세로 4:5",
        "mood_lighting": "소프트 윈도+바운스, 프리미엄 클리닉",
        "must_include": "흰 가운·은은한 브랜딩, 네임핀(가능시)",
        "must_avoid": "강한 그림자, 산만한 배경, 과한 액세서리",
        "consent_required": "필요(의사)",
        "count": "얼굴·반신·전신 변형 3",
        "notes": "사이트 전역 최빈도. 3:2 풍경도 동시 촬영.",
    },
    "src/img/photos/doctors/dr-cha-consultation.webp": {
        "section": "차승연 원장 — 환경(상담)",
        "current_state": "텍스트만",
        "photo_subject": "상담 데스크, 환자차트/태블릿(얼굴 X), 30° 각도.",
        "composition": "미디엄",
        "orientation": "가로 3:2",
        "mood_lighting": "창가 좌측 데이라이트",
        "must_include": "의자, 수첩, 골드 포인트",
        "must_avoid": "차트·화면에 실명, 식별자",
        "consent_required": "필요(의사)",
        "count": "3장",
        "notes": "예약·디자인방식·결정보호·메타셀 푸터 CTA",
    },
    "src/img/photos/doctors/dr-ju-portrait-formal.webp": {
        "section": "주지훈 원장 — 정식(반신) 초상",
        "current_state": "이니셜/텍스트",
        "photo_subject": "인터내셔널 디렉터, 흰 가운, 친근·열려있는 인상(영어 환자용).",
        "composition": "인물(세로)",
        "orientation": "세로 4:5",
        "mood_lighting": "소프트 윈도+바운스",
        "must_include": "흰 가운, 국제·친화적 인상",
        "must_avoid": "과도하게 딱딱/무서움(외국인 이탈)",
        "consent_required": "필요(의사)",
        "count": "변형 3",
        "notes": "LP 저자 byline·영어용 가로 crop.",
    },
    "src/img/photos/doctors/dr-ju-international-consult.webp": {
        "section": "주지훈 원장 — 영어 상담(환경)",
        "current_state": "텍스트만",
        "photo_subject": "iPad(플랜), 데스크 건너 대화(스탠드인·뒷통수만), 제스처.",
        "composition": "미디엄",
        "orientation": "가로 3:2",
        "mood_lighting": "데이+텅스텐 필",
        "must_include": "아이패드(플랜), 명함, 의자 2",
        "must_avoid": "진짜 환자 얼굴, 식별 데이터",
        "consent_required": "필요(의사+스탠드인)",
        "count": "3장",
        "notes": "영어·컨시어지 스토리, 예약·가이드",
    },
    "src/img/photos/location/building-exterior-wide.webp": {
        "section": "건물 전면(넓은 화면)",
        "current_state": "텍스트만",
        "photo_subject": "논현로 868 전면(5층 식별), 보행자 적은 앵글.",
        "composition": "와이드",
        "orientation": "가로 16:9",
        "mood_lighting": "한낮 맑은 날(11시 전후 권장)",
        "must_include": "전면, 가로·주소 맥락",
        "must_avoid": "지배적 행인, 번호판 클로즈",
        "consent_required": "없음",
        "count": "초점거리 3가지",
        "notes": "압구정 페이지 OG 후보.",
    },
    "src/img/photos/location/reception-waiting-wide.webp": {
        "section": "5층 대기/리셥션(위치 증빙)",
        "current_state": "텍스트만",
        "photo_subject": "대기 넓이, 티·플랜트, 벽면 브랜딩(환자 없이).",
        "composition": "와이드",
        "orientation": "가로 16:9",
        "mood_lighting": "따뜻한 데이+액센트",
        "must_include": "브랜딩, 좌석, 티/워터",
        "must_avoid": "대기 환자, 이름 있는 잡지",
        "consent_required": "없음",
        "count": "각도 3",
        "notes": "오픈 전 공실이면 베스트.",
    },
    "src/img/photos/location/apgujeong-rodeo-street.webp": {
        "section": "압구정·로데 거리 맥락",
        "current_state": "텍스트만",
        "photo_subject": "로데 미드블록 — 부티크, 가로수, 프리미엄가 압구정 무드.",
        "composition": "와이드",
        "orientation": "가로 16:9",
        "mood_lighting": "밝고 살짝 desat",
        "must_include": "압구정 로데 식별",
        "must_avoid": "얼굴 식별, 경쟁 클리닉",
        "consent_required": "없음",
        "count": "4 변형",
        "notes": "홈·가이드·블로그 풀 재사용.",
    },
}
