# ruff: noqa: RUF001
"""Korean text fields (P2 rows) for photo shotlist."""

P2: dict[str, dict[str, str]] = {
    "src/img/photos/booking-manage/header-calendar.webp": {
        "section": "예약 관리(헤더)",
        "current_state": "폼/텍스트",
        "photo_subject": "달력+펜(중립면) — 관리·변경 느낌.",
        "composition": "탑뷰",
        "orientation": "가로 3:2",
        "mood_lighting": "소프트 데이",
        "must_include": "날짜 X 달력, 펜, 명함",
        "must_avoid": "실명, 예약",
        "consent_required": "없음",
        "count": "1",
        "notes": "스트립 이미지—선택.",
    },
    "src/img/photos/consult/hero-followup.webp": {
        "section": "빠른문의(컨설트) Hero",
        "current_state": "텍스트만",
        "photo_subject": "데스크·전화(뒤통수) — ‘다시 연락’ 안심.”",
        "composition": "미디엄",
        "orientation": "가로 3:2",
        "mood_lighting": "따뜻·데이",
        "must_include": "가운만 보이는 뒷모습(가능), 노트, 차분",
        "must_avoid": "이름·화면",
        "consent_required": "필요(직원)",
        "count": "1",
        "notes": "낮은 우선. 주로 폼.",
    },
    "src/img/photos/blog/blog-hero-generic-{01-03}.webp": {
        "section": "블로그(EN) — 범용 히어로 풀 3",
        "current_state": "텍스트만",
        "photo_subject": "①해부+마커 ②튠 팜프 ③리셥션·꽃(맥락별로 배정).",
        "composition": "클로즈업/와이드",
        "orientation": "가로 16:9",
        "mood_lighting": "따뜻·데이",
        "must_include": "일관·브랜딩, 환자X",
        "must_avoid": "주제만 너무 구체(범용 유지)",
        "consent_required": "없음",
        "count": "3장(범용)",
        "notes": "에디터·포스트에 매핑, 후일 업그레이드 가능.",
    },
    "src/img/photos/global/footer-dusk.webp": {
        "section": "푸터/연락(황혼·외관)",
        "current_state": "텍스트만",
        "photo_subject": "일몰+창빛·건물(조용한 엔딩).",
        "composition": "와이드",
        "orientation": "가로 16:9",
        "mood_lighting": "황혼+웜",
        "must_include": "건물·빛",
        "must_avoid": "인물, 헤드라이트 과다",
        "consent_required": "없음",
        "count": "2",
        "notes": "보너스. ~18:00·재방문.",
    },
    "src/img/photos/concierge/english-support-candid.webp": {
        "section": "컨시어지(영어) 캔디드",
        "current_state": "텍스트만",
        "photo_subject": "영어·스탠드인(자연) 웃음 톤.",
        "composition": "미디엄",
        "orientation": "가로 3:2",
        "mood_lighting": "따뜻",
        "must_include": "유니폼, 은은한 영문",
        "must_avoid": "과한 포즈",
        "consent_required": "필요(직원+스탠드인)",
        "count": "3",
        "notes": "FAQ·가이드. 과다사용X.",
    },
    "src/img/photos/aftercare/product-set.webp": {
        "section": "스킨케어(애프터) 세트",
        "current_state": "텍스트만",
        "photo_subject": "선·세럼·시트(애프터).",
        "composition": "탑뷰",
        "orientation": "정사각 1:1",
        "mood_lighting": "데이",
        "must_include": "애프터+명함",
        "must_avoid": "무허가 타사",
        "consent_required": "없음",
        "count": "2",
        "notes": "블로그·휴지용.",
    },
    "src/img/photos/location/window-view-apgujeong.webp": {
        "section": "5층 창(전역) — 감성",
        "current_state": "텍스트만",
        "photo_subject": "창+거리(전경) 전경=식물(소프트).",
        "composition": "미디엄",
        "orientation": "가로 3:2",
        "mood_lighting": "데이+실내",
        "must_include": "창, 지구, 식물",
        "must_avoid": "창에 환자, 외부 식별 간판(과다)",
        "consent_required": "없음",
        "count": "2",
        "notes": "분위기·재사용·블로그.",
    },
}
