# ruff: noqa: RUF001
"""Korean text fields (P1 rows) for photo shotlist."""

P1: dict[str, dict[str, str]] = {
    "src/img/photos/signature-lifting/hero-ultherapy-handpiece.webp": {
        "section": "시그니처 리프팅 LP Hero(37행)",
        "current_state": "다크 배경·텍스트",
        "photo_subject": "울쎄라+핸드피스, 의사 손(얼굴X), 젤+패드 위(중간 촬영 앵글).",
        "composition": "미디엄",
        "orientation": "가로 16:9",
        "mood_lighting": "뮤지엄톤, 다크 백",
        "must_include": "울쎄라 밍, 장갑",
        "must_avoid": "환자 얼·피부 노출",
        "consent_required": "필요(의사)",
        "count": "3",
        "notes": "상단 다크(화이트 헤드라인).",
    },
    "src/img/photos/structural-reset/hero-thermage-tip.webp": {
        "section": "스트럭쳐 리셋 LP Hero(35행)",
        "current_state": "다크·텍스트",
        "photo_subject": "써마지 FLX+팁+CPT, 프리미엄 엔지니어링 느낌.",
        "composition": "미디엄",
        "orientation": "가로 16:9",
        "mood_lighting": "뮤지엄톤",
        "must_include": "써마지, 손(선택)",
        "must_avoid": "환자 신체, 사용 후 일회품 노출",
        "consent_required": "없음",
        "count": "3",
        "notes": "프리미엄 VIP 랜딩 톤.",
    },
    "src/img/photos/collagen-builder/hero-skin-booster-tray.webp": {
        "section": "콜라겐 빌더 LP Hero(35행)",
        "current_state": "다크·텍스트",
        "photo_subject": "스킨부스터 바이알(리쥬란/쥬베룩) 트레이+장갑(오버헤드).",
        "composition": "탑뷰",
        "orientation": "가로 16:9",
        "mood_lighting": "뮤지엄+단일 림",
        "must_include": "제조사 밍, 멸균 트레이, 장갑",
        "must_avoid": "부적절한 캡 개방, 환자",
        "consent_required": "없음",
        "count": "3",
        "notes": "‘주입 전 디자인’ 톤.",
    },
    "src/img/photos/filler-chamaka-se/hero-design-mapping.webp": {
        "section": "볼륨·차마카세 LP Hero(35행)",
        "current_state": "다크·텍스트",
        "photo_subject": "해부도·3D 머리 모형+마커(디자인 의도, 실환자 X).",
        "composition": "클로즈업",
        "orientation": "가로 16:9",
        "mood_lighting": "뮤지엄톤",
        "must_include": "해부/맨네킨, 마커, 장갑",
        "must_avoid": "실제 환자 사진, 브랜드 비교 연출",
        "consent_required": "필요(의사)",
        "count": "3",
        "notes": "하모니 섹션과 겸용.",
    },
    "src/img/photos/decision-protection/hero-planning-desk.webp": {
        "section": "결정보호 LP Hero(14행)",
        "current_state": "텍스트만",
        "photo_subject": "iPad(플랜), 종이, 물, 생화 — 인물 없이(사고 유도).",
        "composition": "탑뷰",
        "orientation": "가로 16:9",
        "mood_lighting": "밝은 공기감, 미니멀",
        "must_include": "아이패드(플랜), 노트, 브랜딩",
        "must_avoid": "개인정보, 전화, 이름",
        "consent_required": "없음",
        "count": "3",
        "notes": "메타셀 푸터·디자인방식 intro 재사용.",
    },
    "src/img/photos/design-method/hero-vector-mapping.webp": {
        "section": "디자인방식 LP Hero(37행)",
        "current_state": "텍스트만",
        "photo_subject": "해부 시트+페이스 벡터(손만).",
        "composition": "클로즈업",
        "orientation": "가로 16:9",
        "mood_lighting": "따뜻한 데이+책상램프",
        "must_include": "해부도, 펜, 손",
        "must_avoid": "책상의 환자 사진, 기기로고(과도)",
        "consent_required": "필요(의사, 손만 OK)",
        "count": "3",
        "notes": "해부·디자인 워크플로우 톤.",
    },
    "src/img/photos/design-method/workflow-step-{01-06}.webp": {
        "section": "해부적 디자인 6스텝(130행)",
        "current_state": "텍스트 6칸",
        "photo_subject": "동일 제스: 메모,아이패드,벡터,블루프린트,미세,깊이안전—클로즈6장(정사각).",
        "composition": "클로즈업",
        "orientation": "정사각 1:1",
        "mood_lighting": "데이, 6장 동일",
        "must_include": "동일 책상, 화면마다 손 1쌍 이하",
        "must_avoid": "식별자, 조명 불일치",
        "consent_required": "필요(의사 손)",
        "count": "6장(세트)",
        "notes": "한 세션에 연촬.",
    },
    "src/img/photos/apgujeong/hero-district-clinic.webp": {
        "section": "압구정(외국인) LP Hero(17행)",
        "current_state": "텍스트만",
        "photo_subject": "좌:전면 / 우:스카이라인 분할, 또는 5F 창+지구 맥락.",
        "composition": "와이드",
        "orientation": "가로 16:9",
        "mood_lighting": "맑고 프리미엄",
        "must_include": "압구정 맥락+클리닉 식별",
        "must_avoid": "경쟁 사인",
        "consent_required": "없음",
        "count": "2",
        "notes": "P0로케이션이 촉박하면 합성.",
    },
    "src/img/photos/faq/hero-concierge-english-support.webp": {
        "section": "시술 FAQ Hero(14행)",
        "current_state": "텍스트만",
        "photo_subject": "리셥션+아이패드(영문 UI, 환자 뒷통수).",
        "composition": "미디엄",
        "orientation": "가로 16:9",
        "mood_lighting": "따뜻한 데이",
        "must_include": "유니폼, 영문, 브랜딩",
        "must_avoid": "얼굴, 실제 데이터",
        "consent_required": "필요(직원+스탠드인)",
        "count": "3",
        "notes": "‘영어 응대 실제’ 신뢰.",
    },
    "src/img/photos/guides/hero-printed-guides.webp": {
        "section": "가이드 index Hero(31행)",
        "current_state": "텍스트만",
        "photo_subject": "인쇄 가이드+안경+커피(오버헤드) 입국 전 느낌.",
        "composition": "탑뷰",
        "orientation": "가로 16:9",
        "mood_lighting": "따뜻·에어리",
        "must_include": "브랜딩(플레이스홀더 OK)",
        "must_avoid": "다른 병원 브로셔",
        "consent_required": "없음",
        "count": "2",
        "notes": "서브가이드용 마퀴 crop.",
    },
    "src/img/photos/korean-lifting-guide/hero-devices-lineup.webp": {
        "section": "한국 리프팅 가이드 Hero+카드(16·39행)",
        "current_state": "텍스트만",
        "photo_subject": "울쎄라·써마·온다(올리지오) 핸드피스 라인(오버헤드) 시각 백과.",
        "composition": "탑뷰",
        "orientation": "가로 16:9",
        "mood_lighting": "클리니컬",
        "must_include": "3핸드피스, 깨끗한 패드",
        "must_avoid": "테이프·먼지·불일치 조명",
        "consent_required": "없음",
        "count": "2(오버+30°)",
        "notes": "4카드용 정사각 crop 추가.",
    },
    "src/img/photos/ultherapy-vs-thermage/hero-side-by-side.webp": {
        "section": "울쎄라 vs 써마지 Hero(14행)",
        "current_state": "텍스트만",
        "photo_subject": "두 기기 동일 프레임+중성 패널(우열 없음).",
        "composition": "와이드",
        "orientation": "가로 16:9",
        "mood_lighting": "클리니컬+사이드 필",
        "must_include": "전면+밍",
        "must_avoid": "한쪽만 도드라지게(우열)",
        "consent_required": "없음",
        "count": "2",
        "notes": "균형 프레이밍 필수.",
    },
    "src/img/photos/dermal-fillers/hero-filler-tray.webp": {
        "section": "더말·필러 Hero(15·36행)",
        "current_state": "텍스트만",
        "photo_subject": "냉장 트레이+HA(쥬비·레스·벨·라디) 동등 노출(오버헤드).",
        "composition": "탑뷰",
        "orientation": "가로 16:9",
        "mood_lighting": "클리니컬, 살짝 쿨",
        "must_include": "소비기한 OK 박스, 장갑",
        "must_avoid": "사용된 주사기, 한 브랜드만 강조",
        "consent_required": "없음",
        "count": "2",
        "notes": "브랜드 동등(오해 없이).",
    },
    "src/img/photos/skin-boosters/hero-vial-tray.webp": {
        "section": "스킨부스터·재생 Hero(14·35행)",
        "current_state": "텍스트만",
        "photo_subject": "리쥬/PDRN·쥬베·엑소·스컬(라벨) 정돈(오버헤드).",
        "composition": "탑뷰",
        "orientation": "가로 16:9",
        "mood_lighting": "클리니컬",
        "must_include": "4범주, 멸균 트레이",
        "must_avoid": "한 브랜드 압도, 열린 샤프",
        "consent_required": "없음",
        "count": "2",
        "notes": "카드용 단품 클로즈.",
    },
    "src/img/photos/hair-loss/hero-scalp-treatment.webp": {
        "section": "탈모·두피 Hero(14행)",
        "current_state": "텍스트만",
        "photo_subject": "마네킨 두피+기기, 또는 케어 앰플(실환자 X).",
        "composition": "미디엄",
        "orientation": "가로 16:9",
        "mood_lighting": "클리니컬",
        "must_include": "기기/바이알, 장갑",
        "must_avoid": "실제 두피, 전후사진",
        "consent_required": "없음",
        "count": "2",
        "notes": "저트래픽, 히어로 1면으로 충분.",
    },
    "src/img/photos/how-to-choose/hero-indication-mapping.webp": {
        "section": "리프팅 고르는 법 Hero+카드(14·30행)",
        "current_state": "텍스트만",
        "photo_subject": "4구역(처짐·탄력·윤곽·체류) 해부지+마커(손만).",
        "composition": "클로즈업",
        "orientation": "가로 16:9",
        "mood_lighting": "따뜻한 데이",
        "must_include": "해부도+마킹",
        "must_avoid": "환자 사진, 기기·브랜드명(과다)",
        "consent_required": "필요(의사, 손만)",
        "count": "2",
        "notes": "디자인방식과 동일 조명.",
    },
    "src/img/photos/international-guide/hero-trip-planning-desk.webp": {
        "section": "외국인 가이드 Hero(19행)",
        "current_state": "텍스트만",
        "photo_subject": "여권(표지만/일반), 일정, 명함, 에어팟(오버헤드) 서울·계획 느낌.",
        "composition": "탑뷰",
        "orientation": "가로 16:9",
        "mood_lighting": "따뜻·에어리",
        "must_include": "여권(민감X), 일정, 명함",
        "must_avoid": "사진·페이지, 편명·실명",
        "consent_required": "없음",
        "count": "2",
        "notes": "FAQ용 컨시어지와 페어.",
    },
    "src/img/photos/menu/hero-printed-menu.webp": {
        "section": "메뉴(가격) Hero(111행)",
        "current_state": "다크·텍스트",
        "photo_subject": "차마카세 인쇄 메뉴+스톤+꽃(오버헤드) 스프레드시트 느낌 완화.",
        "composition": "탑뷰",
        "orientation": "가로 16:9",
        "mood_lighting": "뮤지엄",
        "must_include": "브랜딩(플레이스홀더 OK), 스톤",
        "must_avoid": "타 클리닉 가격",
        "consent_required": "없음",
        "count": "2",
        "notes": "가독+프리미엄.",
    },
    "src/img/photos/equipment/ultherapy-handpiece.webp": {
        "section": "장비(라이브러리) — 울쎄라",
        "current_state": "텍스트만",
        "photo_subject": "핸드피스+기기, 은은한 튠 스티커, 시리얼 가림.",
        "composition": "클로즈업",
        "orientation": "정사각 1:1",
        "mood_lighting": "클리니컬",
        "must_include": "울쎄라 밍",
        "must_avoid": "먼지, 잔·젤",
        "consent_required": "없음",
        "count": "각도 3",
        "notes": "시그·스트럭·가이드·vs 다용.",
    },
    "src/img/photos/equipment/thermage-flx-tip.webp": {
        "section": "장비(라이브러리) — 써마지 FLX",
        "current_state": "텍스트만",
        "photo_subject": "CPT+팁, 기기(깨끗).",
        "composition": "클로즈업",
        "orientation": "정사각 1:1",
        "mood_lighting": "클리니컬",
        "must_include": "써마지, 팁 정면",
        "must_avoid": "사용 칼트, 먼지",
        "consent_required": "없음",
        "count": "각도 3",
        "notes": "스트럭·vs 다용.",
    },
    "src/img/photos/equipment/onda-lifting.webp": {
        "section": "장비(라이브러리) — 온다 리프팅",
        "current_state": "텍스트만",
        "photo_subject": "마이크로웨이브·온다 핸드피스(형태 특징).",
        "composition": "클로즈업",
        "orientation": "정사각 1:1",
        "mood_lighting": "클리니컬",
        "must_include": "온다, 깨끗",
        "must_avoid": "뒤 산란(혼잡)",
        "consent_required": "없음",
        "count": "2",
        "notes": "한국·시그.",
    },
    "src/img/photos/equipment/pbm-device.webp": {
        "section": "장비(라이브러리) — PBM(광생체조절)",
        "current_state": "텍스트만",
        "photo_subject": "PBM 헤드+저광 red glow, 환자 없음(미니멀).",
        "composition": "클로즈업",
        "orientation": "정사각 1:1",
        "mood_lighting": "클리니컬+red glow",
        "must_include": "헤드, 은은한 빨강(과노X)",
        "must_avoid": "광원 과다노출",
        "consent_required": "없음",
        "count": "2",
        "notes": "메타셀 카드 핵심.",
    },
    "src/img/photos/equipment/juvelook-rejuran-still.webp": {
        "section": "장비(라이브러리) — 쥬베·리쥬란",
        "current_state": "텍스트만",
        "photo_subject": "쥬베 針+리쥬 박스+멸균 매트(스틸).",
        "composition": "클로즈업",
        "orientation": "정사각 1:1",
        "mood_lighting": "밝은 화이트",
        "must_include": "밍, 로트(가리기)",
        "must_avoid": "캡이 열린 바늘(샤프), 유통기한 지난",
        "consent_required": "없음",
        "count": "3(분리+합)",
        "notes": "콜라겐·스킨·블로그.",
    },
    "src/img/photos/comfort/iv-sedation-chair.webp": {
        "section": "IV(정맥) 진정(메뉴/스트럭쳐)",
        "current_state": "텍스트만",
        "photo_subject": "빈 IV 리클라이너+담요+물(환자 없이).",
        "composition": "미디엄",
        "orientation": "가로 3:2",
        "mood_lighting": "데이+웜 텅",
        "must_include": "리클라·담요·협탁",
        "must_avoid": "시술·모니터 개인정보",
        "consent_required": "없음",
        "count": "2",
        "notes": "프리미엄 감성.",
    },
    "src/img/photos/comfort/recovery-lounge.webp": {
        "section": "리커버리 라운지(메뉴/스트럭쳐)",
        "current_state": "텍스트만",
        "photo_subject": "라운지 와이드, 티, 식물(환자 없이).",
        "composition": "와이드",
        "orientation": "가로 3:2",
        "mood_lighting": "웜 티(진정·프리미엄)",
        "must_include": "착석, 티, 식물",
        "must_avoid": "환자, 사용 타올(과다)",
        "consent_required": "없음",
        "count": "3",
        "notes": "오픈 전 공실.",
    },
    "src/img/photos/rooms/treatment-room-wide.webp": {
        "section": "시술실(전역 재사용)",
        "current_state": "텍스트만",
        "photo_subject": "빈 시술베드+덮인 기기+램프 — 프라이빗·클린.",
        "composition": "와이드",
        "orientation": "가로 3:2",
        "mood_lighting": "웜 클리니컬",
        "must_include": "베드, 드레이프, 터치",
        "must_avoid": "이물함·사용 1회품(과다)",
        "consent_required": "없음",
        "count": "3(실 3곳)",
        "notes": "LP 다용.",
    },
    "src/img/photos/rooms/consultation-room-wide.webp": {
        "section": "상담실(전역)",
        "current_state": "텍스트만",
        "photo_subject": "데스크·아이패드·2의자·램프·해부액자.",
        "composition": "와이드",
        "orientation": "가로 3:2",
        "mood_lighting": "데이+램프",
        "must_include": "2의자, 액자",
        "must_avoid": "차트·가격",
        "consent_required": "없음",
        "count": "2",
        "notes": "예약·디자인·결정.",
    },
    "src/img/photos/gallery/hero-documentation-process.webp": {
        "section": "갤러리 Hero(55행) — ‘크롬’(전후 X)",
        "current_state": "다크·텍스트",
        "photo_subject": "플랜카드+봉투(전후 X, 문서 느낌만).",
        "composition": "탑뷰",
        "orientation": "가로 16:9",
        "mood_lighting": "뮤지엄",
        "must_include": "케이스, 폴더, 장갑",
        "must_avoid": "실제 전·후 이미지(별도 동의)",
        "consent_required": "없음",
        "count": "2",
        "notes": "실전·후는 별도 릴리즈 트랙.",
    },
}
